version: '2'
services:
    cmt-app:
        image: cmt
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://cmt-mariadb:3306/cmt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cmt-mariadb:
        extends:
            file: mariadb.yml
            service: cmt-mariadb
