version: '2'
services:
    cmtproject-app:
        image: cmtproject
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://cmtproject-mariadb:3306/cmtproject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cmtproject-mariadb:
        extends:
            file: mariadb.yml
            service: cmtproject-mariadb
