#!/bin/sh
# husky
# v1.1.0 linux

scriptPath="node_modules/husky/lib/runner/bin.js"
hookName=`basename "$0"`
gitParams="$*"

if ! command -v node >/dev/null 2>&1; then
  echo "Can't find node in PATH, trying to find a node binary on your system"
fi

if [ -f $scriptPath ]; then
  node_modules/run-node/run-node $scriptPath $hookName "$gitParams"
else
  echo "Can't find Husky, skipping $hookName hook"
  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
fi
